package com.example.news.dao;

import com.example.news.dao.impl.GenericDAO;
import com.example.news.mapper.RowMapper;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

@EnabledIfSystemProperty(named = "runDbTests", matches = "true")
public class GenericDaoCategoryCrudIntegrationTest {

    private static final String TEST_CODE = "jdbc-test-category";
    private static final String TEST_NAME = "JDBC Test Category";
    private static final String UPDATED_NAME = "JDBC Test Category Updated";

    private IGenericDAO genericDAO;

    private static class CategoryRow {
        private final Long id;
        private final String name;
        private final String code;
        private final Timestamp createdDate;
        private final Timestamp modifiedDate;

        public CategoryRow(Long id, String name, String code, Timestamp createdDate, Timestamp modifiedDate) {
            this.id = id;
            this.name = name;
            this.code = code;
            this.createdDate = createdDate;
            this.modifiedDate = modifiedDate;
        }

        public Long getId() { return id; }
        public String getName() { return name; }
        public String getCode() { return code; }
        public Timestamp getCreatedDate() { return createdDate; }
        public Timestamp getModifiedDate() { return modifiedDate; }
    }

    private final RowMapper<CategoryRow> categoryMapper = new RowMapper<CategoryRow>() {
        @Override
        public CategoryRow mapRow(ResultSet rs) throws SQLException {
            return new CategoryRow(
                    rs.getLong("id"),
                    rs.getString("name"),
                    rs.getString("code"),
                    rs.getTimestamp("created_date"),
                    rs.getTimestamp("modified_date")
            );
        }
    };

    @BeforeEach
    public void setUp() {
        genericDAO = new GenericDAO();
        cleanupTestData();
    }

    @AfterEach
    public void tearDown() {
        cleanupTestData();
    }

    private void cleanupTestData() {
        genericDAO.delete("DELETE FROM category WHERE code = ?", TEST_CODE);
    }

    @Test
    @DisplayName("Verify complete CRUD lifecycle on Category table using GenericDAO")
    public void testCategoryCrudLifecycle() {
        // Step 1: Precondition cleanup verified
        String selectSql = "SELECT id, name, code, created_date, modified_date FROM category WHERE code = ?";
        CategoryRow initialCheck = genericDAO.queryOne(selectSql, categoryMapper, TEST_CODE);
        assertNull(initialCheck, "Precondition failed: test record already exists");

        String countSql = "SELECT COUNT(*) FROM category";
        long baselineCount = genericDAO.count(countSql);

        // Step 2: CREATE
        String insertSql = "INSERT INTO category (name, code) VALUES (?, ?)";
        long generatedId = genericDAO.insert(insertSql, TEST_NAME, TEST_CODE);
        assertTrue(generatedId > 0, "Insert should return generated positive ID");

        // Step 3: READ ONE
        CategoryRow inserted = genericDAO.queryOne(selectSql, categoryMapper, TEST_CODE);
        assertNotNull(inserted, "Inserted category should be found");
        assertEquals(generatedId, inserted.getId().longValue(), "Retrieved ID should match generated ID");
        assertEquals(TEST_NAME, inserted.getName(), "Name should match inserted name");
        assertEquals(TEST_CODE, inserted.getCode(), "Code should match inserted code");
        assertNotNull(inserted.getCreatedDate(), "Created date should be generated by database");

        // Step 4: READ ALL
        String selectAllSql = "SELECT id, name, code, created_date, modified_date FROM category";
        List<CategoryRow> allCategories = genericDAO.query(selectAllSql, categoryMapper);
        boolean containsTestItem = allCategories.stream().anyMatch(c -> TEST_CODE.equals(c.getCode()));
        assertTrue(containsTestItem, "Category list should contain the newly inserted test category");

        // Step 5: UPDATE
        String updateSql = "UPDATE category SET name = ?, modified_date = CURRENT_TIMESTAMP WHERE code = ?";
        int updatedRows = genericDAO.update(updateSql, UPDATED_NAME, TEST_CODE);
        assertEquals(1, updatedRows, "Exactly 1 row should be updated");

        CategoryRow updated = genericDAO.queryOne(selectSql, categoryMapper, TEST_CODE);
        assertNotNull(updated, "Updated category should be found");
        assertEquals(UPDATED_NAME, updated.getName(), "Category name should reflect update");

        // Step 6: COUNT
        long countAfterInsert = genericDAO.count(countSql);
        assertEquals(baselineCount + 1, countAfterInsert, "Total categories should increase by 1");

        // Step 7: DELETE
        String deleteSql = "DELETE FROM category WHERE code = ?";
        int deletedRows = genericDAO.delete(deleteSql, TEST_CODE);
        assertEquals(1, deletedRows, "Exactly 1 row should be deleted");

        // Step 8: READ AFTER DELETE
        CategoryRow afterDelete = genericDAO.queryOne(selectSql, categoryMapper, TEST_CODE);
        assertNull(afterDelete, "Category should not exist after deletion");

        long countAfterDelete = genericDAO.count(countSql);
        assertEquals(baselineCount, countAfterDelete, "Total categories should return to baseline after delete");
    }
}
